- id: clickbait-commit-messages
  name: clickbait-commit-messages
  entry: env HF_TOKEN=$HF_TOKEN make_clickbaity
  language: python
  always_run: true
  require_serial: true
  description: "Make your commit messages extremely catchy."
  minimum_pre_commit_version: 2.9.2
  args: ["--style", "youtube"]
  stages: [prepare-commit-msg]
